# Generated by Django 3.1.2 on 2020-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'PROFILE',
            },
        ),
    ]
