# Generated by Django 3.0.3 on 2020-11-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201103_1048'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofileinfo',
            table=None,
        ),
    ]
