# Generated by Django 3.0.3 on 2020-11-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201103_1536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofileinfo',
            table='PROFILE',
        ),
    ]
